# Generated by Django 6.0.3 on 2026-03-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_full_name_user_is_business_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_business',
            field=models.BooleanField(default=False),
        ),
    ]
