# Generated by Django 5.2.4 on 2026-03-17 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_verified_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Full name must contain at least one letter.', regex='.*[a-zA-Z\\s].*')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Mobile number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
