# Generated by Django 6.0.2 on 2026-03-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Amount Unpaid'), ('paid', 'Amount Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='received_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], default='pending', max_length=20),
        ),
    ]
