# Generated by Django 6.0.2 on 2026-03-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_status_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('home_delivery', 'Home Delivery'), ('shop_pickup', 'Shop Pickup')], default='home_delivery', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='installation_type',
            field=models.CharField(choices=[('installation_required', 'Worker Installation Required'), ('product_only', 'Product Only')], default='installation required', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('b2b', 'Business')], default='individual', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('razorpay', 'Razorpay')], default='cod', max_length=20),
            preserve_default=False,
        ),
    ]
