# Generated by Django 5.2.4 on 2026-03-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivered_at_order_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
