# Generated by Django 5.2.4 on 2026-03-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('razorpay', 'Razorpay'), ('online', 'Online Payment (Mock)')], max_length=20),
        ),
    ]
