# Generated by Django 6.0.3 on 2026-03-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='build_time',
            field=models.CharField(blank=True, default='4-6 Weeks', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='certification',
            field=models.CharField(blank=True, default='Vaagai Mastercraft Certified', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, default='Natural Oil Rubbed', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='Sustainable Hardwood', max_length=200, null=True),
        ),
    ]
