# Generated by Django 6.0.3 on 2026-03-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admin_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
