# Generated by Django 6.0.3 on 2026-03-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_admin_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
