# Generated by Django 6.0.3 on 2026-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_user_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_seen_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_seen_by_user',
            field=models.BooleanField(default=True),
        ),
    ]
