# Generated by Django 6.0.3 on 2026-03-06 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BDiscountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_discount_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('bulk_threshold', models.PositiveIntegerField(default=10)),
                ('bulk_discount_percent', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'B2B Discount Settings',
                'verbose_name_plural': 'B2B Discount Settings',
            },
        ),
        migrations.CreateModel(
            name='B2BApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=15)),
                ('business_type', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
