from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.units import inch
from io import BytesIO

def generate_analytics_pdf(data, ai_summary):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    
    # Custom Styles for Vaagai Brand
    title_style = ParagraphStyle(
        'VaagaiTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#D4AF37"),
        spaceAfter=30,
        alignment=1 # Center
    )
    
    header_style = ParagraphStyle(
        'VaagaiHeader',
        parent=styles['Heading2'],
        fontSize=18,
        textColor=colors.HexColor("#FFFFFF"),
        backColor=colors.HexColor("#0A0A0A"),
        padding=10,
        spaceBefore=20,
        spaceAfter=15
    )
    
    label_style = ParagraphStyle(
        'VaagaiLabel',
        fontSize=10,
        textColor=colors.HexColor("#888888"),
        spaceAfter=5
    )
    
    value_style = ParagraphStyle(
        'VaagaiValue',
        fontSize=12,
        textColor=colors.HexColor("#FFFFFF"),
        spaceAfter=15,
        fontWeight='Bold'
    )

    story_style = ParagraphStyle(
        'VaagaiStory',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.HexColor("#CCCCCC"),
        lineHeight=1.5,
        spaceAfter=20
    )

    elements = []

    # 1. Header & Title
    elements.append(Paragraph("VAAGAI ACADEMY & ARTIFACTS", title_style))
    elements.append(Paragraph("EXECUTIVE ANALYTICS INTELLIGENCE REPORT", styles['Heading3']))
    elements.append(Spacer(1, 0.5 * inch))

    # 2. KPI Overview
    elements.append(Paragraph("I. COMMERCIAL PERFORMANCE SNAPSHOT", header_style))
    
    kpi_data = [
        ["Metric", "Value"],
        ["Total Revenue", f"INR {data['kpis']['total_revenue']:,}"],
        ["Order Volume", str(data['kpis']['total_orders'])],
        ["Active Clients", str(data['kpis']['total_customers'])],
        ["Avg Order Value", f"INR {data['kpis']['avg_order_value']:,}"],
        ["Artisanal Rating", f"{data['kpis']['avg_rating']} / 5.0"]
    ]
    
    t = Table(kpi_data, colWidths=[2.5*inch, 2.5*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1A1A1A")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#D4AF37")),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#050505")),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#333333")),
        ('FONTSIZE', (0,0), (-1,-1), 10),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 0.5 * inch))

    # 3. Top Products
    elements.append(Paragraph("II. TOP ARTISANAL ASSETS", header_style))
    product_data = [["Product Name", "Units Sold", "Revenue Generated"]]
    for p in data['top_products']:
        product_data.append([p['name'], str(p['sales']), f"INR {p['revenue']:,}"])
    
    pt = Table(product_data, colWidths=[2.5*inch, 1.25*inch, 1.25*inch])
    pt.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1A1A1A")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#D4AF37")),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#333333")),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#050505")),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.white),
    ]))
    elements.append(pt)
    elements.append(PageBreak())

    # 4. AI Strategic Insights
    elements.append(Paragraph("III. AI STRATEGIC SYNTHESIS", header_style))
    elements.append(Paragraph("The following insights were generated by the Artisanal Intelligence Command center based on current business momentum:", label_style))
    elements.append(Spacer(1, 10))
    
    # Process AI summary (assuming markdown format from LLM)
    for line in ai_summary.split('\n'):
        if line.strip():
            elements.append(Paragraph(line, story_style))
    
    elements.append(Spacer(1, 0.5 * inch))
    elements.append(Paragraph("Report generated on " + data.get('generated_at', 'N/A'), label_style))

    doc.build(elements)
    pdf = buffer.getvalue()
    buffer.close()
    return pdf
